#cloud-config
write_files:
- content: |
    {
      "provision" : true
    }
  path: /run/cloud-init/run_provisioning.json
- content: |
    {
      "datacenter": "${datacenter}",
      "domain": "${domain}"
    }
  path: /run/cloud-init/consul/consul_region.json
- content: |
    {
      "encrypt": "${encrypt}"
    }
  path: /run/cloud-init/consul/consul_secrets.json
- content: |
    {
      "retry_join": [
        "provider=azure subscription_id=${subscription} tag_name=consul_server_id tag_value=${environment_id}"
      ]
    }
  path: /run/cloud-init/consul/client/consul_client_location.json
- content: |
    ${consul_cert_bundle}
  encoding: base64
  path: /run/cloud-init/consul/certs/consul_cert_bundle.crt
- content: |
    #
    # See unbound.conf(5) man page, version 1.6.3.
    #
    server:
    local-zone: "${domain}." nodefault
    domain-insecure: "${domain}"

    stub-zone:
    name: "${domain}"
    stub-addr: 127.0.0.1@8600

    forward-zone:
    name: "."
    forward-addr: ${vnet_forward_ip}
  path: /run/cloud-init/unbound/unbound_zones.conf
