#cloud-config
write_files:
- content: |
    {
      "provision" : true
    }
  path: /run/cloud-init/run_provisioning.json
- content: |
    {
      "datacenter": "${datacenter}",
      "domain": "integrationtest"
    }
  path: /run/cloud-init/consul/consul_region.json
- content: |
    {
      "encrypt": "${encrypt}"
    }
  path: /run/cloud-init/consul/consul_secrets.json
- content: |
    {
      "retry_join": [
        "provider=azure datacenter=${datacenter} category=${category} consul_node=server tenant_id=${azure_tenant_id} subscription_id=${azure_subscription_id} "
      ]
    }
  path: /run/cloud-init/consul/client/consul_server_location.json
- content: |
    #
    # See unbound.conf(5) man page, version 1.6.3.
    #
    server:
    local-zone: "${domain}." nodefault
    domain-insecure: "${domain}"

    stub-zone:
    name: "${domain}"
    stub-addr: 127.0.0.1@8600

    forward-zone:
    name: "."
    forward-addr: ${vnet_forward_ip}
  path: /run/cloud-init/unbound/unbound_zones.conf
